#ENV http_proxy http://10.176.205.3:8090
FROM alpine:latest
MAINTAINER Adil MAMOUNE <adil.mamoune@gmail.com>
#RUN apt-get update 
RUN echo "Test de creer une image alpine @@@@@@=========|||||||"
#    && apt-get install -y \
#        gnuplot
WORKDIR /home/gnuplot
